# Generated by Django 2.0 on 2018-08-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='rollno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='student_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
